# Generated by Django 2.2.7 on 2020-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=250)),
                ('optiona', models.CharField(default='', max_length=100)),
                ('optionb', models.CharField(default='', max_length=100)),
                ('optionc', models.CharField(default='', max_length=100)),
                ('optiond', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
                ('catagory', models.CharField(choices=[('sports', 'Sports'), ('movies', 'Movies'), ('maths', 'Maths'), ('generalknowledge', 'GeneralKnowledge')], max_length=20)),
            ],
            options={
                'ordering': ('-catagory',),
            },
        ),
    ]
