# Generated by Django 2.2.7 on 2020-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions1',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='optiona',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='optionb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='optionc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='optiond',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
