# Generated by Django 2.2.7 on 2020-02-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200219_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions1',
        ),
    ]
