# Generated by Django 2.2.7 on 2020-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
