# Generated by Django 2.2.7 on 2020-02-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_student_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
