# Generated by Django 2.2.7 on 2020-02-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200218_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
    ]
