# Generated by Django 2.2.7 on 2020-02-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_questions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
