# Generated by Django 2.2.7 on 2020-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_questions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='catagory',
            field=models.CharField(choices=[('readings', 'Readings'), ('grammars', 'Grammars'), ('conversations', 'Conversations'), ('generalknowledge', 'GeneralKnowledge')], max_length=20),
        ),
    ]
