# Generated by Django 2.2.7 on 2020-02-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20200223_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='newcategory',
        ),
    ]
