# Generated by Django 3.0.3 on 2020-04-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200426_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='catagory',
        ),
    ]
